<?php if(Mage::helper('connector')->isEnabled()){ //Verify module status 
	$development_mode = "false"; // Edit to "false" when using in production
?>

<?php $javascript_code = Mage::helper('connector')->getJavascriptCode(); ?>

<script type="text/javascript">
//<![CDATA[
	var _mm = _mm || [];
	(function() {
	var a,b,c;a = function(f) { return function() {_mm.push([f].concat(Array.prototype.slice.call(arguments,0)))}};b=["identify","track","addItems"]; for(c=0;c<b.length;c++){_mm[b[c]]=a(b[c])};
	var t = document.createElement('script'),s = document.getElementsByTagName('script')[0]; t.async = true;t.id = 'mm-tracker';
	t.setAttribute('install-code', '<?php echo $javascript_code; ?>'); t.setAttribute('development', <?php echo $development_mode; ?>);
	t.src = 'https://s3-ap-southeast-1.amazonaws.com/asset.minematic.com/js/mm-track.min.js';s.parentNode.insertBefore(t, s);
	})();
//]]>
</script>

<?php
if(Mage::getSingleton('customer/session')->isLoggedIn()){
		 // Load the customer's data
	    $customer = Mage::getSingleton('customer/session')->getCustomer();
	 	// Getting data
		$customer_id             = $customer->getId();
	?>

<script type="text/javascript">
_mm.identify({id: '<?php echo $customer_id; ?>' });
</script>

<?php } ?>


<?php
if($this->getRequest()->getControllerName()=='product'){
	//Get product data
	$productObject = Mage::registry('current_product');
	$product_id    = $productObject->getId();
	?>

<script type="text/javascript">
_mm.track('VIEW', {id:'<?php echo $product_id; ?>'});
</script>

<?php } ?>

<?php  } //Closing IF that validates module status?>